### ISSUE TITLE
Cannot find main file

### ISSUE THREAD

**Issue by Keyaku** [ShawnFunke/vs_code_http_server_and_html_preview#4]
I'm getting the message:
`Cannot find main file 'index.html', please make sure that you are in the correct directory!`

And I have no idea why. I'm obviously working on the workspace with `index.html` at the root.

If I use "with current file" I can't seem to use CSS files (apparently? Cross-Origin stuff is kind of weird, it currently is accepting Facebook Graph API requests and local images, so I'm unsure what's going on).

**Comment by ShawnFunke** [comment]
I'll look into the issue today and hopefully fix it

**Comment by ShawnFunke** [comment]
I'm guessing you were running Linux. The new version `2.2.2` should fix this issue.
